language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm run cover

os:
  - osx
  - linux

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | ./node_modules/.bin/codacy-coverage"